# Generated by Django 3.2 on 2021-04-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('location_street_address_line1', models.CharField(max_length=300)),
                ('location_street_address_line2', models.CharField(max_length=300)),
                ('location_city', models.CharField(max_length=80)),
                ('location_state', models.CharField(max_length=4)),
                ('location_zipcode', models.CharField(max_length=12)),
                ('location_lat', models.DecimalField(decimal_places=9, max_digits=12)),
                ('location_long', models.DecimalField(decimal_places=9, max_digits=12)),
            ],
        ),
    ]
