# Generated by Django 3.2 on 2021-05-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210506_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='loc_hist_file',
            field=models.FileField(upload_to=''),
        ),
    ]
