# Generated by Django 3.2 on 2021-05-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_profile_loc_hist_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='loc_hist_file',
            field=models.FileField(upload_to='loc_hist/'),
        ),
    ]
