# Generated by Django 3.2 on 2021-05-08 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_profile_loc_hist_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='loc_hist_file',
            field=models.FileField(upload_to='loc_hist/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])]),
        ),
    ]
