# Generated by Django 3.2 on 2021-05-19 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_profile_locationhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_lat',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_long',
            new_name='long',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_street_address_line1',
            new_name='street_address_line1',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_street_address_line2',
            new_name='street_address_line2',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_zipcode',
            new_name='zipcode',
        ),
    ]
