# Generated by Django 3.2 on 2021-05-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_loc_hist_file_locationhistory_zip_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationhistory',
            name='dir',
            field=models.CharField(default='./', max_length=200),
            preserve_default=False,
        ),
    ]
