# Generated by Django 3.2 on 2021-05-27 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessions', '0001_initial'),
        ('main', '0012_locationhistory_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session'),
        ),
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='locationhistory',
            name='point_file',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='locationhistory',
            name='sem_dir',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='locationhistory',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session'),
        ),
        migrations.AlterField(
            model_name='location',
            name='street_address_line2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='locationhistory',
            name='dir',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
