# Generated by Django 3.2 on 2021-05-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210527_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='session',
        ),
        migrations.AddField(
            model_name='location',
            name='session_key',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
